apiVersion: observability.antnsn.dev/v1alpha1
kind: ContactPoint
metadata:
  labels:
    app.kubernetes.io/name: alerts-operator
    app.kubernetes.io/managed-by: kustomize
  name: contactpoint-sample
spec:
  # TODO(user): Add fields here
